services:
  app:
    build: .
    command: go run main.go
    environment:
      DB_HOST: pgsql-main.haops.beans
      DB_USER: barista
      DB_PASSWORD: coffeebeans
      DB_NAME: coffee
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8080:8080"